database:
  type: 'rdbms'
  driver: '$DB_DRIVER'
  host: '$DB_HOST'
  port: $DB_PORT
  db: '$DB_NAME'
  username: '$DB_USER'
  password: '$DB_PASS'
  pool_size: 10
secrets_path: '/etc/labler/secrets/'